---
kind: pipeline
type: docker
name: style

platform:
  os: linux
  arch: amd64

steps:
- name: drone fmt
  image: letfn/drone
  settings:
    task: fmt

- name: drone lint
  image: letfn/drone
  settings:
    task: lint

-----
kind: pipeline
type: docker
name: requirements

platform:
  os: linux
  arch: amd64

steps:
- name: update requirements.txt
  image: letfn/python
  commands:
  - . /app/venv/bin/activate
  - pip-compile /drone/src/requirements.in -o /tmp/requirements.txt
  - if test -w . ; then cp /tmp/requirements.txt requirements.txt; else diff requirements.txt /tmp/requirements.txt || true;  fi

...
